[tool.flake8]
max-line-length = 79

[tool.isort]
profile = "black"
line_length=79
force_sort_within_sections = true
combine_as_imports = true
include_trailing_comma = true
skip = "migrations"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.ropeproject
  | migrations
)/
'''
